// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeammateApi.Data;

#nullable disable

namespace TeammateApi.Migrations
{
    [DbContext(typeof(TeammateContext))]
    [Migration("20231210184230_help")]
    partial class help
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("TeammateApi.Data.UserAdress", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("MapLatitude")
                        .HasColumnType("TEXT")
                        .HasColumnName("map_latitude");

                    b.Property<string>("MapLongitude")
                        .HasColumnType("TEXT")
                        .HasColumnName("map_longitude");

                    b.Property<string>("UserUid")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_uid");

                    b.ToTable("user_adresses", (string)null);
                });

            modelBuilder.Entity("TeammateApi.Data.UserProfile", b =>
                {
                    b.Property<string>("UserUid")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_uid");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("UserUid");

                    b.ToTable("user_profile", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
